// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1.0/protocol/user_service.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	api/v1.0/protocol/user_service.proto

It has these top-level messages:
	User
	ListUserRequestType
	ListUserResponseType
	RegisterUserResponseType
	RegisterUserRequestType
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ListUserRequestType struct {
}

func (m *ListUserRequestType) Reset()                    { *m = ListUserRequestType{} }
func (m *ListUserRequestType) String() string            { return proto.CompactTextString(m) }
func (*ListUserRequestType) ProtoMessage()               {}
func (*ListUserRequestType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListUserResponseType struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUserResponseType) Reset()                    { *m = ListUserResponseType{} }
func (m *ListUserResponseType) String() string            { return proto.CompactTextString(m) }
func (*ListUserResponseType) ProtoMessage()               {}
func (*ListUserResponseType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListUserResponseType) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type RegisterUserResponseType struct {
}

func (m *RegisterUserResponseType) Reset()                    { *m = RegisterUserResponseType{} }
func (m *RegisterUserResponseType) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserResponseType) ProtoMessage()               {}
func (*RegisterUserResponseType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RegisterUserRequestType struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *RegisterUserRequestType) Reset()                    { *m = RegisterUserRequestType{} }
func (m *RegisterUserRequestType) String() string            { return proto.CompactTextString(m) }
func (*RegisterUserRequestType) ProtoMessage()               {}
func (*RegisterUserRequestType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RegisterUserRequestType) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*ListUserRequestType)(nil), "protocol.ListUserRequestType")
	proto.RegisterType((*ListUserResponseType)(nil), "protocol.ListUserResponseType")
	proto.RegisterType((*RegisterUserResponseType)(nil), "protocol.RegisterUserResponseType")
	proto.RegisterType((*RegisterUserRequestType)(nil), "protocol.RegisterUserRequestType")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	ListUser(ctx context.Context, in *ListUserRequestType, opts ...grpc.CallOption) (*ListUserResponseType, error)
	RegisterUser(ctx context.Context, in *RegisterUserRequestType, opts ...grpc.CallOption) (*RegisterUserResponseType, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListUserRequestType, opts ...grpc.CallOption) (*ListUserResponseType, error) {
	out := new(ListUserResponseType)
	err := grpc.Invoke(ctx, "/protocol.UserService/ListUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequestType, opts ...grpc.CallOption) (*RegisterUserResponseType, error) {
	out := new(RegisterUserResponseType)
	err := grpc.Invoke(ctx, "/protocol.UserService/RegisterUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	ListUser(context.Context, *ListUserRequestType) (*ListUserResponseType, error)
	RegisterUser(context.Context, *RegisterUserRequestType) (*RegisterUserResponseType, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UserService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListUserRequestType))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserRequestType))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1.0/protocol/user_service.proto",
}

func init() { proto.RegisterFile("api/v1.0/protocol/user_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0x2c, 0xc8, 0xd4,
	0x2f, 0x33, 0xd4, 0x33, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x2d,
	0x4e, 0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0x8b, 0x0a, 0x71, 0xc0,
	0x24, 0x95, 0x74, 0xb8, 0x58, 0x42, 0x8b, 0x53, 0x8b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13,
	0x33, 0x73, 0x24, 0x98, 0xc0, 0x42, 0x10, 0x8e, 0x92, 0x28, 0x97, 0xb0, 0x4f, 0x66, 0x71, 0x09,
	0x48, 0x47, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x49, 0x48, 0x65, 0x41, 0xaa, 0x92, 0x0d, 0x97,
	0x08, 0x42, 0xb8, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15, 0x24, 0x2e, 0xa4, 0xc2, 0xc5, 0x0a, 0xb2,
	0xbc, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x4f, 0x0f, 0x66, 0xad, 0x1e, 0x58, 0x29,
	0x44, 0x52, 0x49, 0x8a, 0x4b, 0x22, 0x28, 0x35, 0x3d, 0xb3, 0xb8, 0x24, 0xb5, 0x08, 0xdd, 0x04,
	0x25, 0x7d, 0x2e, 0x71, 0x54, 0x39, 0xb8, 0xa5, 0x08, 0x17, 0x32, 0x22, 0xb9, 0xd0, 0x68, 0x33,
	0x23, 0x17, 0x37, 0x48, 0x65, 0x30, 0xc4, 0xbf, 0x42, 0xde, 0x5c, 0x1c, 0x30, 0xa7, 0x09, 0xc9,
	0x22, 0xec, 0xc7, 0xe2, 0x0b, 0x29, 0x39, 0x6c, 0xd2, 0x48, 0x6e, 0x61, 0x10, 0x0a, 0xe7, 0xe2,
	0x41, 0x76, 0x8d, 0x90, 0x22, 0x42, 0x07, 0x0e, 0x57, 0x4a, 0x29, 0xe1, 0x52, 0x82, 0x6c, 0x70,
	0x12, 0x1b, 0x58, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x7a, 0xfd, 0xbf, 0xbe, 0x01,
	0x00, 0x00,
}
